cardapio-digital:
  host: 'https://api.iorion19.app/api'
  token: '655280075f41e'

sischef:
  host: 'https://sistema.sischef.com/api-v2/webhook/integracao/OT'
  token: '2904cd7f-e24c-43a1-a58a-ed339d12efcf'

delivery-much:
  autenticacao:
    host: 'https://devmuch-api.auth0.com/oauth/token'
    client_id: 'SDOMDenG3WHgWVDHrmpmOScIbVyUPAai'
    client_secret: 'mp5RXKdLlSyjw2OX08PQ3yiBX8J2S7J2xZ2BMrnu0F_0qs6_VIBuNui3MExi3fJm'
    username: 'iorion19'
    password: '5fUQvsrxf09y'
    grant_type: 'password'
  api:
    host: 'https://api.devmuch.io'
    provedor: '63861e4f2c7ng'
    id_externo: '123e4567-e89b-12d3-a456-426614174000'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardapio_digital
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 5000