cardapio-digital:
  host: 'https://api.iorion19.app/api'
  token: '64e36be22f4e0'

sischef:
  host: 'https://sistema.sischef.com/api-v2/webhook/integracao/OT'
  token: '2904cd7f-e24c-43a1-a58a-ed339d12efcf'